import type { Metadata } from "next";
import {  Open_Sans, Raleway } from "next/font/google";
import { Providers } from "./providers";

const openSans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open-sans",
});

const raleway = Raleway({ subsets: ["latin"], variable: "--font-raleway" });

// const brunoAceSc = Bruno_Ace_SC({
//   subsets: ["latin"],
//   variable: "--font-bruce-ace-sc",
//   weight: "400",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <main
        className={` ${openSans.className} ${raleway.variable} font-sans`}
      >
        <Providers>{children}</Providers>
      </main>
    </html>
  );
}
